name: Blocker
description: You're stuck and need something to proceed.
title: "[BLOCKED] <short title>"
labels:
  - blocked
  - question
body:
  - type: textarea
    id: problem
    attributes:
      label: What's blocking you
      placeholder: I can't finish X because Y isn't available or decided yet.
    validations:
      required: true

  - type: textarea
    id: need
    attributes:
      label: What you need
      placeholder: Decision, review, API change, data, example input, etc.
    validations:
      required: true

  - type: input
    id: related
    attributes:
      label: Related issue or PR
      placeholder: #123 or link
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      options:
        - today
        - this week
        - not urgent
      default: 0
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Unblocked when
      placeholder: What must happen so you can continue.
    validations:
      required: true
