name: Bug
description: Something in main is broken.
title: "[BUG] <short title>"
labels:
  - bug
body:
  - type: textarea
    id: observed
    attributes:
      label: What happened
      placeholder: Crash, wrong output, error message
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What should happen
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      placeholder: Steps and inputs
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Done when
      placeholder: What proves it’s fixed
    validations:
      required: true
