name: Infra
description: Repo/process work (docs, templates, rules).
title: "[INFRA] <short title>"
labels:
  - chore
  - documentation
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Add PR and issue templates
    validations:
      required: true
  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      placeholder: Files or settings that will exist/change after this change
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Done when
      placeholder: How we’ll confirm it works in the GitHub UI
    validations:
      required: true
