name: Task
description: Single unit of work (feature or change).
title: "[TASK] <short title>"
labels:
  - enhancement
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Implement Student model with GPA and completed courses
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      placeholder: What’s included. What’s out of scope.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance
      placeholder: How we’ll check this is done
    validations:
      required: true
  - type: checkboxes
    id: sidebar
    attributes:
      label: Sidebar setup
      description: Set these in the right sidebar.
      options:
        - label: I set Assignee
        - label: I set Milestone
        - label: I set Labels
